apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobportal-ingress
spec:
  rules:
  - host: jobportal.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 3500

